services:
    # App section
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: laravel_db
            DB_USERNAME: laravel_user
            DB_PASSWORD: laravel_password

            BROADCAST_DRIVER: log
            CACHE_DRIVER: redis
            QUEUE_CONNECTION: redis
            SESSION_DRIVER: file
            SESSION_LIFETIME: "120"

            REDIS_HOST: redis
            REDIS_PORT: 6379
        depends_on:
            - mysql
            - redis
        networks:
            - laravel_network

    # Nginx section
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel_network

    # MySQL section
    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_password

        # For access from outside the container
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel_network

    # Redis section
    redis:
        image: redis:alpine
        container_name: redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - laravel_network

    node:
        image: node:18-alpine
        container_name: node
        working_dir: /var/www
        ports:
            - "3000:3000"
            - "3001:3001"
        volumes:
            - ./:/var/www
        networks:
            - laravel_network
        command: sh -c "npm install && npm run dev"

# Volumes section
volumes:
    db_data:

# Networks section
networks:
    laravel_network:
        driver: bridge
